name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download vicious
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download \
            --repo vicious-rebirth/vicious \
            --pattern "web.zip"
          unzip web.zip

      - name: Package
        run: |
          mv src package
          mv web/* package/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
