name: Deploy

on:
  workflow_dispatch:

jobs:
  vicious-website:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VICIOUS_WEBSITE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone repo
        run: git clone git@github.com:vicious-rebirth/website.git

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: website
        run: |
          pnpm install

      - name: Build Tool
        working-directory: website
        run: |
          pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vicious-website
          path: website/dist

  vicious-explorer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VICIOUS_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone repo
        run: git clone git@github.com:vicious-rebirth/vicious.git

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build WASM
        working-directory: vicious
        run: |
          GOOS=js GOARCH=wasm go build -ldflags "-s" -o build/main.wasm js/main.go
          cd build
          cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VICIOUS_EXPLORER_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone repo
        run: git clone git@github.com:vicious-rebirth/vicious-explorer.git

      - name: Copy WASM
        run: |
          mkdir vicious-explorer/public
          cp -r vicious/build vicious-explorer/public/go

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: vicious-explorer
        run: |
          pnpm install

      - name: Build Tool
        working-directory: vicious-explorer
        run: |
          pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vicious-explorer
          path: vicious-explorer/dist

  package:
    runs-on: ubuntu-latest
    needs: [vicious-explorer, vicious-website]
    steps:
      - name: Download vicious-website
        uses: actions/download-artifact@v4
        with:
          name: vicious-website
          path: package

      - name: Download vicious-explorer
        uses: actions/download-artifact@v4
        with:
          name: vicious-explorer
          path: package/vicious-explorer

      - name: Fix assets
        run: mv package/vicious-explorer/assets/* package/assets/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
